- name: install erlang dependencies
  become: yes
  apt:
    name:
      - ca-certificates
      - gnupg
      - apt-transport-https
    state: present

- name: add erlang GPG key
  become: yes
  apt_key:
    url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    state: present

- name: add erlang repository
  become: yes
  apt_repository:
    repo: deb https://packages.erlang-solutions.com/ubuntu focal contrib
    state: present

- name: install erlang
  become: yes
  apt:
    name:
      - esl-erlang
      - elixir
    state: present